esphome:
  name: salt_lamp
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: "Home"
    password: "1234512345"
  manual_ip:
    static_ip: 10.0.0.34
    gateway: 10.0.0.254
    subnet: 255.255.255.0
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Salt Lamp Fallback Hotspot"
    password: "1234512345"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

substitutions:
  plug_name: salt_lamp
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "925"
  

time:
  - platform: homeassistant
    id: homeassistant_time
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: True
    name: "${plug_name}_button"
    on_press:
      - switch.toggle: switch1
    internal: true

output:
  - platform: gpio
    pin: GPIO15
    id: relay
  - platform: gpio
    pin: GPIO02
    inverted: True
    id: led1

status_led:
  pin:
    number: GPIO00
    inverted: True

switch:
- platform: template
  id: switch1
  icon: mdi:crystal-ball
  optimistic: true
  name: "Salt Lamp"
  turn_on_action:
    - output.turn_on: relay
    - output.turn_on: led1
  turn_off_action:
    - output.turn_off: relay
    - output.turn_off: led1

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "Salt Lamp Current"
      internal: true
    voltage:
      name: "Salt Lamp Voltage"
      internal: true
    power:
      name: "Salt Lamp Power"
      icon: mdi:flash-circle
      id: power

  - platform: total_daily_energy
    name: "Salt Lamp Daily Energy Use"
    power_id: "power"
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:clock-alert